### ISSUE TITLE
[Library Bug] - Unable to import homeassistant_api

### ISSUE THREAD

**Issue by mangoose002** [GrandMoff100/HomeAssistantAPI#156]
Hi all,

Whatever I do, I get the following error when importing homeassistant_api
Traceback (most recent call last):
  File "hass.py", line 2, in <module>
    from homeassistant_api import Client as HASSClient
  File "/usr/local/lib/python3.8/dist-packages/homeassistant_api/__init__.py", line 26, in <module>
    from .client import Client
  File "/usr/local/lib/python3.8/dist-packages/homeassistant_api/client.py", line 5, in <module>
    from .rawasyncclient import RawAsyncClient
  File "/usr/local/lib/python3.8/dist-packages/homeassistant_api/rawasyncclient.py", line 27, in <module>
    from .processing import AsyncResponseType, Processing
  File "/usr/local/lib/python3.8/dist-packages/homeassistant_api/processing.py", line 109, in <module>
    def process_json(response: ResponseType) -> dict[str, Any]:
TypeError: 'type' object is not subscriptable

The code that generates the issue is:
import os
from homeassistant_api import Client as HASSClient

The OS is Ubuntu 20.04.6 LTS
Python Version is: Python 3.8.10
Library version: 4.1.1.post2

I am surely missing something but I do not know what.

Thanks in advance for your help

**Comment by mangoose002** [comment]
I found what the problem is.
It need to use Python 3.9 at least.

After the update, everything works fine.
You should add this information in the prerequisites of the addon.

Regards

**Comment by GrandMoff100** [comment]
Oh yeah, the typing annotations of 3.9 or later aren't backwards compatible. I can redo the annotations to be supported by earlier versions of python.
