### ISSUE TITLE
[Library Bug] AsyncClient.request fails with ContentTypeError

### ISSUE THREAD

**Issue by GrandMoff100** [GrandMoff100/HomeAssistantAPI#27]
**Describe the bug**
AsyncClient fails to initialize because it can't parse the `text/plain` mimetype response as a json. Check need to be added.

**To Reproduce**
```py
import asyncio
from homeassistant_api import AsyncClient

async def main():
    async with AsyncClient(url, token) as client:
        pass

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Expected behavior**
AsyncClient is expected to check the mimetype and only decode to json if the mimetype allows. Instead it always decodes to json, regardless of the mimetype.
 
**Traceback**
```
Traceback (most recent call last):
  File "dev.py", line 18, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "dev.py", line 11, in main
    async with AsyncClient(url, token) as client:
  File "/home/runner/HomeAssistantAPI/homeassistant_api/_async/asyncclient.py", line 34, in __aenter__
    await self.check_api_running()
  File "/home/runner/HomeAssistantAPI/homeassistant_api/_async/asyncclient.py", line 165, in check_api_running
    res = await self.request('')
  File "/home/runner/HomeAssistantAPI/homeassistant_api/_async/asyncclient.py", line 64, in request
    return await self.response_logic(resp, return_text)
  File "/home/runner/HomeAssistantAPI/homeassistant_api/_async/asyncclient.py", line 71, in response_logic
    return await response.json()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('http://hass-api-testing-env.grandmoff100.repl.co/api/')
```

**Desktop (please complete the following information):**
 - OS: Ubuntu Docker
 - OS Version 20.04
 - HomeAssistantAPI Version: 2.2.0

**Comment by GrandMoff100** [comment]
Mimetype checking is now added
