### ISSUE TITLE
[Library Bug] measurement stopped with error after 3 minutes

### ISSUE THREAD

**Issue by pejotigrek** [GrandMoff100/HomeAssistantAPI#55]
**Describe the bug**
I started measurement, everything was fine and suddenly after 3 minutes it stopped. all devices still available on the network, no outage that I am aware of. 

```bash
2022-02-14 09:17:08,748 [INFO] Selected Light controller: hass
? Select the color mode?  color_temp
? Do you want to generate model.json?  Yes
? Specify the full light model name  Yeelight YLDP02YL 600lm 1700K-6500K WiFi RGB Bulb
? Which powermeter (manufacturer, model) do you use to take the measurement?  Gosund SP111 v1.1
? Do you want to gzip CSV files?  Yes
? Are you measuring multiple lights. In some situations it helps to connect multiple lights to be able to measure low currents.  No
? Select the light?  light.yeelight
? What model is your light? Ex: LED1837R5  YLDP02YL
2022-02-14 09:17:48,190 [INFO] Measuring standby power. Waiting for 20 seconds...
2022-02-14 09:18:09,386 [INFO] Start taking measurements for color mode: color_temp
2022-02-14 09:18:09,387 [INFO] Waiting 10 seconds...
2022-02-14 09:18:19,398 [INFO] Changing light to: ColorTempVariation(bri=1, ct=153)
2022-02-14 09:18:22,502 [INFO] Measured power: 2.1
2022-02-14 09:18:22,503 [INFO] Changing light to: ColorTempVariation(bri=1, ct=163)
2022-02-14 09:18:25,589 [INFO] Measured power: 2.5
2022-02-14 09:18:25,590 [INFO] Changing light to: ColorTempVariation(bri=1, ct=173)
2022-02-14 09:18:28,727 [INFO] Measured power: 1.8
2022-02-14 09:18:28,727 [INFO] Changing light to: ColorTempVariation(bri=1, ct=183)
2022-02-14 09:18:31,907 [INFO] Measured power: 1.7
2022-02-14 09:18:31,908 [INFO] Changing light to: ColorTempVariation(bri=1, ct=193)
2022-02-14 09:18:35,039 [INFO] Measured power: 1.8
2022-02-14 09:18:35,039 [INFO] Changing light to: ColorTempVariation(bri=1, ct=203)
2022-02-14 09:18:38,135 [INFO] Measured power: 1.7
2022-02-14 09:18:38,136 [INFO] Changing light to: ColorTempVariation(bri=1, ct=213)
2022-02-14 09:18:41,231 [INFO] Measured power: 2.1
2022-02-14 09:18:41,231 [INFO] Changing light to: ColorTempVariation(bri=1, ct=223)
2022-02-14 09:18:44,368 [INFO] Measured power: 2.2
2022-02-14 09:18:44,369 [INFO] Changing light to: ColorTempVariation(bri=1, ct=233)
2022-02-14 09:18:47,448 [INFO] Measured power: 1.7
2022-02-14 09:18:47,449 [INFO] Changing light to: ColorTempVariation(bri=1, ct=243)
2022-02-14 09:18:50,631 [INFO] Measured power: 1.9
2022-02-14 09:18:50,632 [INFO] Changing light to: ColorTempVariation(bri=1, ct=253)
2022-02-14 09:18:53,776 [INFO] Measured power: 2.1
2022-02-14 09:18:53,777 [INFO] Changing light to: ColorTempVariation(bri=1, ct=263)
2022-02-14 09:18:56,967 [INFO] Measured power: 1.9
2022-02-14 09:18:56,968 [INFO] Changing light to: ColorTempVariation(bri=1, ct=273)
2022-02-14 09:19:00,161 [INFO] Measured power: 1.9
2022-02-14 09:19:00,162 [INFO] Changing light to: ColorTempVariation(bri=1, ct=283)
2022-02-14 09:19:03,239 [INFO] Measured power: 1.8
2022-02-14 09:19:03,240 [INFO] Changing light to: ColorTempVariation(bri=1, ct=293)
2022-02-14 09:19:06,320 [INFO] Measured power: 1.9
2022-02-14 09:19:06,321 [INFO] Changing light to: ColorTempVariation(bri=1, ct=303)
2022-02-14 09:19:09,492 [INFO] Measured power: 2.0
2022-02-14 09:19:09,492 [INFO] Changing light to: ColorTempVariation(bri=1, ct=313)
2022-02-14 09:19:12,567 [INFO] Measured power: 2.1
2022-02-14 09:19:12,568 [INFO] Changing light to: ColorTempVariation(bri=1, ct=323)
2022-02-14 09:19:15,637 [INFO] Measured power: 2.0
2022-02-14 09:19:15,638 [INFO] Changing light to: ColorTempVariation(bri=1, ct=333)
2022-02-14 09:19:18,712 [INFO] Measured power: 2.0
2022-02-14 09:19:18,713 [INFO] Changing light to: ColorTempVariation(bri=1, ct=343)
2022-02-14 09:19:21,843 [INFO] Measured power: 1.7
2022-02-14 09:19:21,844 [INFO] Changing light to: ColorTempVariation(bri=1, ct=353)
2022-02-14 09:19:24,916 [INFO] Measured power: 1.8
2022-02-14 09:19:24,917 [INFO] Changing light to: ColorTempVariation(bri=1, ct=363)
2022-02-14 09:19:27,994 [INFO] Measured power: 1.8
2022-02-14 09:19:27,995 [INFO] Changing light to: ColorTempVariation(bri=1, ct=373)
2022-02-14 09:19:31,071 [INFO] Measured power: 1.9
2022-02-14 09:19:31,072 [INFO] Changing light to: ColorTempVariation(bri=1, ct=383)
2022-02-14 09:19:34,147 [INFO] Measured power: 1.9
2022-02-14 09:19:34,148 [INFO] Changing light to: ColorTempVariation(bri=1, ct=393)
2022-02-14 09:19:37,335 [INFO] Measured power: 1.7
2022-02-14 09:19:37,336 [INFO] Changing light to: ColorTempVariation(bri=1, ct=403)
2022-02-14 09:19:40,428 [INFO] Measured power: 1.6
2022-02-14 09:19:40,428 [INFO] Changing light to: ColorTempVariation(bri=1, ct=413)
2022-02-14 09:19:43,505 [INFO] Measured power: 1.7
2022-02-14 09:19:43,506 [INFO] Changing light to: ColorTempVariation(bri=1, ct=423)
2022-02-14 09:19:46,589 [INFO] Measured power: 1.5
2022-02-14 09:19:46,590 [INFO] Changing light to: ColorTempVariation(bri=1, ct=433)
2022-02-14 09:19:49,722 [INFO] Measured power: 1.5
2022-02-14 09:19:49,723 [INFO] Changing light to: ColorTempVariation(bri=1, ct=443)
2022-02-14 09:19:52,833 [INFO] Measured power: 1.6
2022-02-14 09:19:52,834 [INFO] Changing light to: ColorTempVariation(bri=1, ct=453)
2022-02-14 09:19:55,975 [INFO] Measured power: 2.2
2022-02-14 09:19:55,976 [INFO] Changing light to: ColorTempVariation(bri=1, ct=463)
2022-02-14 09:19:59,091 [INFO] Measured power: 1.7
2022-02-14 09:19:59,092 [INFO] Changing light to: ColorTempVariation(bri=1, ct=473)
2022-02-14 09:20:02,178 [INFO] Measured power: 1.5
2022-02-14 09:20:02,179 [INFO] Changing light to: ColorTempVariation(bri=1, ct=483)
2022-02-14 09:20:05,286 [INFO] Measured power: 1.7
2022-02-14 09:20:05,287 [INFO] Changing light to: ColorTempVariation(bri=1, ct=493)
2022-02-14 09:20:08,435 [INFO] Measured power: 1.7
2022-02-14 09:20:08,436 [INFO] Changing light to: ColorTempVariation(bri=1, ct=503)
2022-02-14 09:20:11,522 [INFO] Measured power: 1.4
2022-02-14 09:20:11,522 [INFO] Changing light to: ColorTempVariation(bri=1, ct=513)
2022-02-14 09:20:14,651 [INFO] Measured power: 2.0
2022-02-14 09:20:14,652 [INFO] Changing light to: ColorTempVariation(bri=1, ct=523)
2022-02-14 09:20:17,794 [INFO] Measured power: 1.5
2022-02-14 09:20:17,794 [INFO] Changing light to: ColorTempVariation(bri=1, ct=533)
2022-02-14 09:20:20,963 [INFO] Measured power: 1.5
2022-02-14 09:20:20,964 [INFO] Changing light to: ColorTempVariation(bri=1, ct=543)
2022-02-14 09:20:24,104 [INFO] Measured power: 1.6
2022-02-14 09:20:24,104 [INFO] Changing light to: ColorTempVariation(bri=1, ct=553)
2022-02-14 09:20:27,182 [INFO] Measured power: 1.5
2022-02-14 09:20:27,183 [INFO] Changing light to: ColorTempVariation(bri=1, ct=563)
2022-02-14 09:20:30,285 [INFO] Measured power: 2.0
2022-02-14 09:20:30,286 [INFO] Changing light to: ColorTempVariation(bri=1, ct=573)
2022-02-14 09:20:33,396 [INFO] Measured power: 2.0
2022-02-14 09:20:33,397 [INFO] Changing light to: ColorTempVariation(bri=1, ct=583)
2022-02-14 09:20:36,530 [INFO] Measured power: 1.9
2022-02-14 09:20:36,530 [INFO] Changing light to: ColorTempVariation(bri=1, ct=588)
2022-02-14 09:20:39,595 [INFO] Measured power: 1.8
2022-02-14 09:20:39,596 [INFO] Changing light to: ColorTempVariation(bri=6, ct=153)
2022-02-14 09:20:39,640 [INFO] Extra waiting for significant CT change...
2022-02-14 09:20:52,805 [INFO] Measured power: 2.1
2022-02-14 09:20:52,806 [INFO] Changing light to: ColorTempVariation(bri=6, ct=163)
2022-02-14 09:20:55,880 [INFO] Measured power: 2.0
2022-02-14 09:20:55,881 [INFO] Changing light to: ColorTempVariation(bri=6, ct=173)
2022-02-14 09:20:59,137 [INFO] Measured power: 1.9
2022-02-14 09:20:59,137 [INFO] Changing light to: ColorTempVariation(bri=6, ct=183)
2022-02-14 09:21:02,306 [INFO] Measured power: 2.6
2022-02-14 09:21:02,306 [INFO] Changing light to: ColorTempVariation(bri=6, ct=193)
2022-02-14 09:21:05,423 [INFO] Measured power: 2.3
2022-02-14 09:21:05,424 [INFO] Changing light to: ColorTempVariation(bri=6, ct=203)
If this happened, please report it at https://github.com/GrandMoff100/HomeAssistantAPI/issues with the request status code and the request content
Traceback (most recent call last):
  File "measure.py", line 544, in <module>
    main()
  File "measure.py", line 541, in main
    measure.start()
  File "measure.py", line 186, in start
    self.light_controller.change_light_state(
  File "/app/light_controller/hass.py", line 31, in change_light_state
    self.client.trigger_service('light', 'turn_on', **json)
  File "/usr/local/lib/python3.8/site-packages/homeassistant_api/client.py", line 185, in trigger_service
    data = self.request(
  File "/usr/local/lib/python3.8/site-packages/homeassistant_api/rawapi.py", line 59, in request
    return self.response_logic(resp)
  File "/usr/local/lib/python3.8/site-packages/homeassistant_api/rawapi.py", line 64, in response_logic
    return processing.process()
  File "/usr/local/lib/python3.8/site-packages/homeassistant_api/processing.py", line 73, in process
    raise UnexpectedStatusCodeError(self.response.status_code, self.response.content)
homeassistant_api.errors.UnexpectedStatusCodeError: Homeassistant return response with an unrecognized status code 500.
b'500 Internal Server Error\n\nServer got itself in trouble'
```

**To Reproduce**
1. Start measure
2. Wait about 3 minutes of correct behavior
3. See error

**Expected behavior**
I'd like to be able to finish the measurement so I can provide new bulb models into repository.

**Screenshots**
![temp_screen](https://user-images.githubusercontent.com/10796588/153841077-a98ee461-fbea-44a3-98f8-a6b339d9d048.jpg)

**Desktop (please complete the following information):**
 - OS: Debian
 - OS Version: 11 (bullseye)
 - HomeAssistantAPI Version: can't find API version, but: HomeAssistant core-2022.2.6, supervisor-2022.01.1

**Additional context**
I've tried hs & color_temp modes - both with the same error.

**Comment by GrandMoff100** [comment]
Hi! Thanks for opening an issue. Can you post your homeassistant logs relevant to the Internal Server Error? Considering that the error itself happened in Homeassistant Core, in order to resolve it we need to look at the server side logs in addition to your client logs (which you've already posted.)

**Comment by GrandMoff100** [comment]
I believe this is related to https://github.com/home-assistant/core/issues/64884

**Comment by GrandMoff100** [comment]
From what I've researched your issue is actually a bug with the `yeelight` library, rather than Home Assistant, or `homeassistant_api`. But good news, there is [an open PR](https://gitlab.com/stavros/python-yeelight/-/merge_requests/95) on yeelights repository that once merged and shipped to pypi should fix your issue. But in the meantime there isn't much we can do.

**Comment by GrandMoff100** [comment]
Yeah, happy to help. Have fun with your homeassistant adventures!
